//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelianceSRCreation.MDMReferenceData {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/information/CanonicalDataModel/ReferenceDataInquiry/")]
    public partial class InternalException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string reasonField;
        
        private string codeField;
        
        private string detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/information/CanonicalDataModel/ReferenceDataInquiry/")]
    public partial class LookUpValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ofTypeField;
        
        private string lovTypeField;
        
        private string lovNameField;
        
        private string lovDescField;
        
        private string systemField;
        
        private string lovCodeField;
        
        private LookUpValue[] lookUpValue1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ofType {
            get {
                return this.ofTypeField;
            }
            set {
                this.ofTypeField = value;
                this.RaisePropertyChanged("ofType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lovType {
            get {
                return this.lovTypeField;
            }
            set {
                this.lovTypeField = value;
                this.RaisePropertyChanged("lovType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lovName {
            get {
                return this.lovNameField;
            }
            set {
                this.lovNameField = value;
                this.RaisePropertyChanged("lovName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string lovDesc {
            get {
                return this.lovDescField;
            }
            set {
                this.lovDescField = value;
                this.RaisePropertyChanged("lovDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("system");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lovCode {
            get {
                return this.lovCodeField;
            }
            set {
                this.lovCodeField = value;
                this.RaisePropertyChanged("lovCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LookUpValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public LookUpValue[] LookUpValue1 {
            get {
                return this.lookUpValue1Field;
            }
            set {
                this.lookUpValue1Field = value;
                this.RaisePropertyChanged("LookUpValue1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/integration/services/common/schema/ReferenceDataInquiry/")]
    public partial class LookupParentValueRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LookUpValue lookupValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LookUpValue lookupValue {
            get {
                return this.lookupValueField;
            }
            set {
                this.lookupValueField = value;
                this.RaisePropertyChanged("lookupValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.example.com/1383718943481", ConfigurationName="MDMReferenceData.ReferenceDataInquiryV1dot2")]
    public interface ReferenceDataInquiryV1dot2 {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/) of message lookupParentValueRequest does not match the default value (http://xmlns.example.com/1383718943481)
        [System.ServiceModel.OperationContractAttribute(Action="/lookupParentValue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RelianceSRCreation.MDMReferenceData.InternalException[]), Action="/lookupParentValue", Name="lookupParentValueException", Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RelianceSRCreation.MDMReferenceData.lookupParentValueResponse lookupParentValue(RelianceSRCreation.MDMReferenceData.lookupParentValueRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/lookupParentValue", ReplyAction="*")]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupParentValueResponse> lookupParentValueAsync(RelianceSRCreation.MDMReferenceData.lookupParentValueRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/) of message lookupRelatedValueRequest does not match the default value (http://xmlns.example.com/1383718943481)
        [System.ServiceModel.OperationContractAttribute(Action="/lookupRelatedValue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RelianceSRCreation.MDMReferenceData.InternalException[]), Action="/lookupRelatedValue", Name="lookupRelatedValueException", Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RelianceSRCreation.MDMReferenceData.lookupRelatedValueResponse lookupRelatedValue(RelianceSRCreation.MDMReferenceData.lookupRelatedValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/lookupRelatedValue", ReplyAction="*")]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupRelatedValueResponse> lookupRelatedValueAsync(RelianceSRCreation.MDMReferenceData.lookupRelatedValueRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/) of message translateValueRequest does not match the default value (http://xmlns.example.com/1383718943481)
        [System.ServiceModel.OperationContractAttribute(Action="/translateValue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RelianceSRCreation.MDMReferenceData.InternalException[]), Action="/translateValue", Name="translateValueException", Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RelianceSRCreation.MDMReferenceData.translateValueResponse1 translateValue(RelianceSRCreation.MDMReferenceData.translateValueRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/translateValue", ReplyAction="*")]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.translateValueResponse1> translateValueAsync(RelianceSRCreation.MDMReferenceData.translateValueRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/) of message lookupHierarchicalValueRequest does not match the default value (http://xmlns.example.com/1383718943481)
        [System.ServiceModel.OperationContractAttribute(Action="/lookupHierarchicalValue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RelianceSRCreation.MDMReferenceData.InternalException[]), Action="/lookupHierarchicalValue", Name="lookupHierarchicalValueException", Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueResponse1 lookupHierarchicalValue(RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/lookupHierarchicalValue", ReplyAction="*")]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueResponse1> lookupHierarchicalValueAsync(RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/) of message lookupValueRequest does not match the default value (http://xmlns.example.com/1383718943481)
        [System.ServiceModel.OperationContractAttribute(Action="/lookupValue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(RelianceSRCreation.MDMReferenceData.InternalException[]), Action="/lookupValue", Name="lookupValueException", Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RelianceSRCreation.MDMReferenceData.lookupValueResponse1 lookupValue(RelianceSRCreation.MDMReferenceData.lookupValueRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/lookupValue", ReplyAction="*")]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupValueResponse1> lookupValueAsync(RelianceSRCreation.MDMReferenceData.lookupValueRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lookupParentValue", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class lookupParentValueRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RelianceSRCreation.MDMReferenceData.LookupParentValueRequest lookupParentValueRequest;
        
        public lookupParentValueRequest1() {
        }
        
        public lookupParentValueRequest1(RelianceSRCreation.MDMReferenceData.LookupParentValueRequest lookupParentValueRequest) {
            this.lookupParentValueRequest = lookupParentValueRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lookupParentValueResponse", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class lookupParentValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lookupParentValueResponse", Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("valueList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupParentValueResponse1;
        
        public lookupParentValueResponse() {
        }
        
        public lookupParentValueResponse(RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupParentValueResponse1) {
            this.lookupParentValueResponse1 = lookupParentValueResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lookupRelatedValue", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class lookupRelatedValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lookupRelatedValueRequest", Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lookupValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupRelatedValueRequest1;
        
        public lookupRelatedValueRequest() {
        }
        
        public lookupRelatedValueRequest(RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupRelatedValueRequest1) {
            this.lookupRelatedValueRequest1 = lookupRelatedValueRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lookupRelatedValueResponse", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class lookupRelatedValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lookupRelatedValueResponse", Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lookupValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupRelatedValueResponse1;
        
        public lookupRelatedValueResponse() {
        }
        
        public lookupRelatedValueResponse(RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupRelatedValueResponse1) {
            this.lookupRelatedValueResponse1 = lookupRelatedValueResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/integration/services/common/schema/ReferenceDataInquiry/")]
    public partial class TranslateValueRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LookUpValue lookupValueField;
        
        private LookUpValue[] valueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LookUpValue lookupValue {
            get {
                return this.lookupValueField;
            }
            set {
                this.lookupValueField = value;
                this.RaisePropertyChanged("lookupValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LookUpValue[] valueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
                this.RaisePropertyChanged("valueList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/integration/services/common/schema/ReferenceDataInquiry/")]
    public partial class TranslateValueResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LookUpValue lookupValueField;
        
        private LookUpValue[] valueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LookUpValue lookupValue {
            get {
                return this.lookupValueField;
            }
            set {
                this.lookupValueField = value;
                this.RaisePropertyChanged("lookupValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LookUpValue[] valueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
                this.RaisePropertyChanged("valueList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="translateValue", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class translateValueRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RelianceSRCreation.MDMReferenceData.TranslateValueRequest translateValueRequest;
        
        public translateValueRequest1() {
        }
        
        public translateValueRequest1(RelianceSRCreation.MDMReferenceData.TranslateValueRequest translateValueRequest) {
            this.translateValueRequest = translateValueRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="translateValueResponse", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class translateValueResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RelianceSRCreation.MDMReferenceData.TranslateValueResponse translateValueResponse;
        
        public translateValueResponse1() {
        }
        
        public translateValueResponse1(RelianceSRCreation.MDMReferenceData.TranslateValueResponse translateValueResponse) {
            this.translateValueResponse = translateValueResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/integration/services/common/schema/ReferenceDataInquiry/")]
    public partial class LookupHierarchicalValueRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LookUpValue lookupValueField;
        
        private DataRecord dataRecordField;
        
        private LookUpValue parentLookupValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LookUpValue lookupValue {
            get {
                return this.lookupValueField;
            }
            set {
                this.lookupValueField = value;
                this.RaisePropertyChanged("lookupValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DataRecord dataRecord {
            get {
                return this.dataRecordField;
            }
            set {
                this.dataRecordField = value;
                this.RaisePropertyChanged("dataRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public LookUpValue parentLookupValue {
            get {
                return this.parentLookupValueField;
            }
            set {
                this.parentLookupValueField = value;
                this.RaisePropertyChanged("parentLookupValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/information/CanonicalDataModel/ReferenceDataInquiry/")]
    public partial class DataRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long totalRecordsField;
        
        private bool totalRecordsFieldSpecified;
        
        private TimePeriod timePeriodField;
        
        private string pagingSizeField;
        
        private string offsetValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long totalRecords {
            get {
                return this.totalRecordsField;
            }
            set {
                this.totalRecordsField = value;
                this.RaisePropertyChanged("totalRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRecordsSpecified {
            get {
                return this.totalRecordsFieldSpecified;
            }
            set {
                this.totalRecordsFieldSpecified = value;
                this.RaisePropertyChanged("totalRecordsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public TimePeriod timePeriod {
            get {
                return this.timePeriodField;
            }
            set {
                this.timePeriodField = value;
                this.RaisePropertyChanged("timePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string pagingSize {
            get {
                return this.pagingSizeField;
            }
            set {
                this.pagingSizeField = value;
                this.RaisePropertyChanged("pagingSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=3)]
        public string offsetValue {
            get {
                return this.offsetValueField;
            }
            set {
                this.offsetValueField = value;
                this.RaisePropertyChanged("offsetValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/information/DataTypes/ReferenceDataInquiry/")]
    public partial class TimePeriod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> startDateTimeField;
        
        private bool startDateTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> endDateTimeField;
        
        private bool endDateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> startDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
                this.RaisePropertyChanged("startDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateTimeSpecified {
            get {
                return this.startDateTimeFieldSpecified;
            }
            set {
                this.startDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("startDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> endDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
                this.RaisePropertyChanged("endDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateTimeSpecified {
            get {
                return this.endDateTimeFieldSpecified;
            }
            set {
                this.endDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("endDateTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/integration/services/common/schema/ReferenceDataInquiry/")]
    public partial class LookupHierarchicalValueResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DataRecord dataRecordField;
        
        private LookUpValue lookupValueField;
        
        private LookUpValue parentLookupValueField;
        
        private LookUpValue[] valueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DataRecord dataRecord {
            get {
                return this.dataRecordField;
            }
            set {
                this.dataRecordField = value;
                this.RaisePropertyChanged("dataRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LookUpValue lookupValue {
            get {
                return this.lookupValueField;
            }
            set {
                this.lookupValueField = value;
                this.RaisePropertyChanged("lookupValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public LookUpValue parentLookupValue {
            get {
                return this.parentLookupValueField;
            }
            set {
                this.parentLookupValueField = value;
                this.RaisePropertyChanged("parentLookupValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public LookUpValue[] valueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
                this.RaisePropertyChanged("valueList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lookupHierarchicalValue", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class lookupHierarchicalValueRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RelianceSRCreation.MDMReferenceData.LookupHierarchicalValueRequest lookupHierarchicalValueRequest;
        
        public lookupHierarchicalValueRequest1() {
        }
        
        public lookupHierarchicalValueRequest1(RelianceSRCreation.MDMReferenceData.LookupHierarchicalValueRequest lookupHierarchicalValueRequest) {
            this.lookupHierarchicalValueRequest = lookupHierarchicalValueRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lookupHierarchicalValueResponse", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class lookupHierarchicalValueResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RelianceSRCreation.MDMReferenceData.LookupHierarchicalValueResponse lookupHierarchicalValueResponse;
        
        public lookupHierarchicalValueResponse1() {
        }
        
        public lookupHierarchicalValueResponse1(RelianceSRCreation.MDMReferenceData.LookupHierarchicalValueResponse lookupHierarchicalValueResponse) {
            this.lookupHierarchicalValueResponse = lookupHierarchicalValueResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/integration/services/common/schema/ReferenceDataInquiry/")]
    public partial class LookupValueRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LookUpValue lookupValueField;
        
        private LookUpValue[] valueListField;
        
        private DataRecord dataRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LookUpValue lookupValue {
            get {
                return this.lookupValueField;
            }
            set {
                this.lookupValueField = value;
                this.RaisePropertyChanged("lookupValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LookUpValue[] valueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
                this.RaisePropertyChanged("valueList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DataRecord dataRecord {
            get {
                return this.dataRecordField;
            }
            set {
                this.dataRecordField = value;
                this.RaisePropertyChanged("dataRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.jio.ril.com/integration/services/common/schema/ReferenceDataInquiry/")]
    public partial class LookupValueResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LookUpValue lookupValueField;
        
        private LookUpValue[] valueListField;
        
        private DataRecord dataRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LookUpValue lookupValue {
            get {
                return this.lookupValueField;
            }
            set {
                this.lookupValueField = value;
                this.RaisePropertyChanged("lookupValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LookUpValue[] valueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
                this.RaisePropertyChanged("valueList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DataRecord dataRecord {
            get {
                return this.dataRecordField;
            }
            set {
                this.dataRecordField = value;
                this.RaisePropertyChanged("dataRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lookupValue", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class lookupValueRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RelianceSRCreation.MDMReferenceData.LookupValueRequest lookupValueRequest;
        
        public lookupValueRequest1() {
        }
        
        public lookupValueRequest1(RelianceSRCreation.MDMReferenceData.LookupValueRequest lookupValueRequest) {
            this.lookupValueRequest = lookupValueRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lookupValueResponse", WrapperNamespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", IsWrapped=true)]
    public partial class lookupValueResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.jio.ril.com/integration/services/common/ReferenceDataInquiry/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RelianceSRCreation.MDMReferenceData.LookupValueResponse lookupValueResponse;
        
        public lookupValueResponse1() {
        }
        
        public lookupValueResponse1(RelianceSRCreation.MDMReferenceData.LookupValueResponse lookupValueResponse) {
            this.lookupValueResponse = lookupValueResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReferenceDataInquiryV1dot2Channel : RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReferenceDataInquiryV1dot2Client : System.ServiceModel.ClientBase<RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2>, RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2 {
        
        public ReferenceDataInquiryV1dot2Client() {
        }
        
        public ReferenceDataInquiryV1dot2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReferenceDataInquiryV1dot2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataInquiryV1dot2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReferenceDataInquiryV1dot2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RelianceSRCreation.MDMReferenceData.lookupParentValueResponse RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.lookupParentValue(RelianceSRCreation.MDMReferenceData.lookupParentValueRequest1 request) {
            return base.Channel.lookupParentValue(request);
        }
        
        public RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupParentValue(RelianceSRCreation.MDMReferenceData.LookupParentValueRequest lookupParentValueRequest) {
            RelianceSRCreation.MDMReferenceData.lookupParentValueRequest1 inValue = new RelianceSRCreation.MDMReferenceData.lookupParentValueRequest1();
            inValue.lookupParentValueRequest = lookupParentValueRequest;
            RelianceSRCreation.MDMReferenceData.lookupParentValueResponse retVal = ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).lookupParentValue(inValue);
            return retVal.lookupParentValueResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupParentValueResponse> RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.lookupParentValueAsync(RelianceSRCreation.MDMReferenceData.lookupParentValueRequest1 request) {
            return base.Channel.lookupParentValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupParentValueResponse> lookupParentValueAsync(RelianceSRCreation.MDMReferenceData.LookupParentValueRequest lookupParentValueRequest) {
            RelianceSRCreation.MDMReferenceData.lookupParentValueRequest1 inValue = new RelianceSRCreation.MDMReferenceData.lookupParentValueRequest1();
            inValue.lookupParentValueRequest = lookupParentValueRequest;
            return ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).lookupParentValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RelianceSRCreation.MDMReferenceData.lookupRelatedValueResponse RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.lookupRelatedValue(RelianceSRCreation.MDMReferenceData.lookupRelatedValueRequest request) {
            return base.Channel.lookupRelatedValue(request);
        }
        
        public RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupRelatedValue(RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupRelatedValueRequest1) {
            RelianceSRCreation.MDMReferenceData.lookupRelatedValueRequest inValue = new RelianceSRCreation.MDMReferenceData.lookupRelatedValueRequest();
            inValue.lookupRelatedValueRequest1 = lookupRelatedValueRequest1;
            RelianceSRCreation.MDMReferenceData.lookupRelatedValueResponse retVal = ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).lookupRelatedValue(inValue);
            return retVal.lookupRelatedValueResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupRelatedValueResponse> RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.lookupRelatedValueAsync(RelianceSRCreation.MDMReferenceData.lookupRelatedValueRequest request) {
            return base.Channel.lookupRelatedValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupRelatedValueResponse> lookupRelatedValueAsync(RelianceSRCreation.MDMReferenceData.LookUpValue[] lookupRelatedValueRequest1) {
            RelianceSRCreation.MDMReferenceData.lookupRelatedValueRequest inValue = new RelianceSRCreation.MDMReferenceData.lookupRelatedValueRequest();
            inValue.lookupRelatedValueRequest1 = lookupRelatedValueRequest1;
            return ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).lookupRelatedValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RelianceSRCreation.MDMReferenceData.translateValueResponse1 RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.translateValue(RelianceSRCreation.MDMReferenceData.translateValueRequest1 request) {
            return base.Channel.translateValue(request);
        }
        
        public RelianceSRCreation.MDMReferenceData.TranslateValueResponse translateValue(RelianceSRCreation.MDMReferenceData.TranslateValueRequest translateValueRequest) {
            RelianceSRCreation.MDMReferenceData.translateValueRequest1 inValue = new RelianceSRCreation.MDMReferenceData.translateValueRequest1();
            inValue.translateValueRequest = translateValueRequest;
            RelianceSRCreation.MDMReferenceData.translateValueResponse1 retVal = ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).translateValue(inValue);
            return retVal.translateValueResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.translateValueResponse1> RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.translateValueAsync(RelianceSRCreation.MDMReferenceData.translateValueRequest1 request) {
            return base.Channel.translateValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.translateValueResponse1> translateValueAsync(RelianceSRCreation.MDMReferenceData.TranslateValueRequest translateValueRequest) {
            RelianceSRCreation.MDMReferenceData.translateValueRequest1 inValue = new RelianceSRCreation.MDMReferenceData.translateValueRequest1();
            inValue.translateValueRequest = translateValueRequest;
            return ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).translateValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueResponse1 RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.lookupHierarchicalValue(RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueRequest1 request) {
            return base.Channel.lookupHierarchicalValue(request);
        }
        
        public RelianceSRCreation.MDMReferenceData.LookupHierarchicalValueResponse lookupHierarchicalValue(RelianceSRCreation.MDMReferenceData.LookupHierarchicalValueRequest lookupHierarchicalValueRequest) {
            RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueRequest1 inValue = new RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueRequest1();
            inValue.lookupHierarchicalValueRequest = lookupHierarchicalValueRequest;
            RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueResponse1 retVal = ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).lookupHierarchicalValue(inValue);
            return retVal.lookupHierarchicalValueResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueResponse1> RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.lookupHierarchicalValueAsync(RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueRequest1 request) {
            return base.Channel.lookupHierarchicalValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueResponse1> lookupHierarchicalValueAsync(RelianceSRCreation.MDMReferenceData.LookupHierarchicalValueRequest lookupHierarchicalValueRequest) {
            RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueRequest1 inValue = new RelianceSRCreation.MDMReferenceData.lookupHierarchicalValueRequest1();
            inValue.lookupHierarchicalValueRequest = lookupHierarchicalValueRequest;
            return ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).lookupHierarchicalValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RelianceSRCreation.MDMReferenceData.lookupValueResponse1 RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.lookupValue(RelianceSRCreation.MDMReferenceData.lookupValueRequest1 request) {
            return base.Channel.lookupValue(request);
        }
        
        public RelianceSRCreation.MDMReferenceData.LookupValueResponse lookupValue(RelianceSRCreation.MDMReferenceData.LookupValueRequest lookupValueRequest) {
            RelianceSRCreation.MDMReferenceData.lookupValueRequest1 inValue = new RelianceSRCreation.MDMReferenceData.lookupValueRequest1();
            inValue.lookupValueRequest = lookupValueRequest;
            RelianceSRCreation.MDMReferenceData.lookupValueResponse1 retVal = ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).lookupValue(inValue);
            return retVal.lookupValueResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupValueResponse1> RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2.lookupValueAsync(RelianceSRCreation.MDMReferenceData.lookupValueRequest1 request) {
            return base.Channel.lookupValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<RelianceSRCreation.MDMReferenceData.lookupValueResponse1> lookupValueAsync(RelianceSRCreation.MDMReferenceData.LookupValueRequest lookupValueRequest) {
            RelianceSRCreation.MDMReferenceData.lookupValueRequest1 inValue = new RelianceSRCreation.MDMReferenceData.lookupValueRequest1();
            inValue.lookupValueRequest = lookupValueRequest;
            return ((RelianceSRCreation.MDMReferenceData.ReferenceDataInquiryV1dot2)(this)).lookupValueAsync(inValue);
        }
    }
}
